name: Testing telegram notification

on:[push]

jobs:
  send-notif-on-success:
    uses: ./.github/workflows/send-telegram.yml
    secrets: inherit # MUST PUT THIS!

  send-notif-on-failure:
    uses: ./.github/workflows/send-telegram.yml
    secrets: inherit # MUST PUT THIS!
