name: tg-notify
on: [push, pull_request]
jobs:
  send-notif-on-success:
    uses: ./.github/workflows/tg-notify.yml
    secrets: inherit # MUST PUT THIS!
     message: |
            "${{ github.actor }}" created commit:
            Commit Message : ${{ github.event.commits[0].message }}
            
            Repository: ${{ github.repository }}
            
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}

  send-notif-on-failure:
    uses: ./.github/workflows/tg-notify.yml
    secrets: inherit # MUST PUT THIS
